### ISSUE TITLE
composer require landofcoder/module-product-reviews

### ISSUE THREAD

**Issue by hassanas** [landofcoder/module-product-reviews#28]
unable to install this module using composer

[Composer\Downloader\TransportException]                                                                                                                                                                 
  The "http://repo.packagist.org/p/landofcoder/module-product-reviews%24981ca2503c73268b7030d62546d4991f31ba9e507bd217ca251c8cd82dbb6afc.json" file could not be downloaded: php_network_getaddresses: ge  
  taddrinfo failed: Name or service not known                                                                                                                                                              
  failed to open stream: php_network_getaddresses: getaddrinfo failed: Name or service not known

**Comment by landofcoder** [comment]
Hi @hassanas 

Thanks you for your reporting!
I just tested composer installation for the module and it is working fine.

Run: 
`composer require landofcoder/module-product-reviews`

Then run magento 2 setup command:
`bin/magento setup:upgrade -vvv`

**Comment by hassanas** [comment]
its php version issue, changing to php7.4 issue resolved
