### ISSUE TITLE
php bin/magento setup:upgrade

### ISSUE THREAD

**Issue by hassanas** [landofcoder/module-product-reviews#29]
setup:upgrade command generating following error:

Installing data... SQLSTATE[42S02]: Base table or view not found: 1146 Table 'rating_option_vote' doesn't exist, query was: SELECT *, SUM(rate_vote.percent) AS sum, COUNT(*) AS count, SUM(rate_vote.percent)/COUNT(*) AS average FROM rating_option_vote as rate_vote WHERE review_id = 1

**Comment by landofcoder** [comment]
Hi @hassanas

Thanks you for your reporting!
We updated the module file and fix the issue, please setup the module again.
The PR to fix for issue: https://github.com/landofcoder/module-product-reviews/pull/30

**Comment by hassanas** [comment]
I already get table name with $connection but in this module its not returning table name with prefix.
