### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by saravananvelu** [landofcoder/module-product-reviews#31]
When switching from developer to production mode, facing the below issue,

Compilation was started.
%message% 0/9 [>---------------------------]   0% < 1 sec 99.0 MiBProxies code generation... 0/9 [>---------------------------]   0% < 1 sec 99.0 MiB
Proxies code generation... 1/9 [===>------------------------]  11% 1 sec 105.0 MiB
Repositories code generation... 1/9 [===>------------------------]  11% 1 sec 105.0 MiBPHP Fatal error:  Could not check compatibility between Lof\ProductReviews\Model\VerifyRepository::execute(int $customerId, Lof\ProductReviews\Model\VerifyInterface $data): bool and Lof\ProductReviews\Api\VerifyRepositoryInterface::execute(int $customerId, Lof\ProductReviews\Api\Data\VerifyInterface $data): bool, because class Lof\ProductReviews\Model\VerifyInterface is not available in app/code/Lof/ProductReviews/Model/VerifyRepository.php on line 69

**Comment by landofcoder** [comment]
Hi @saravananvelu 
Please try to update file https://github.com/landofcoder/module-product-reviews/blob/master/Model/VerifyRepository.php
for your site, or setup module version 1.0.8 to fix the issue.
